// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT-PRJFeqRf4eju2RA0l-pz5eEKtraVKA',
    appId: '1:1088198675613:android:9f187b168583ca81911874',
    messagingSenderId: '1088198675613',
    projectId: 'data-5f273',
    storageBucket: 'data-5f273.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHoVVBDQspjGwFUk8cUA6mANcQjMP85xg',
    appId: '1:1088198675613:ios:9432ff94e46a764d911874',
    messagingSenderId: '1088198675613',
    projectId: 'data-5f273',
    storageBucket: 'data-5f273.appspot.com',
    iosClientId: '1088198675613-apit5qn9k6m1dc74srj2pm4bddt0gapp.apps.googleusercontent.com',
    iosBundleId: 'pete.jijo.polls',
  );

  static const FirebaseOptions web  = FirebaseOptions(
    apiKey: "AIzaSyBShqAZPIeLQjHepNi-Acu1Z3qrBGZha4E",
    authDomain: "data-5f273.firebaseapp.com",
    databaseURL: "https://data-5f273-default-rtdb.firebaseio.com",
    projectId: "data-5f273",
    storageBucket: "data-5f273.appspot.com",
    messagingSenderId: "1088198675613",
    appId: "1:1088198675613:web:bc63ab5058009d6b911874",
    measurementId: "G-402M4PK2KM"
  );
}




